//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class management
    {
        public int id { get; set; }
        public string student_name { get; set; }
        public string teacher_name { get; set; }
        public string course { get; set; }
        public string date { get; set; }
        public string start_time { get; set; }
        public string finish_time { get; set; }
    }
}
