//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class course_managementEntities : DbContext
    {
        public course_managementEntities()
            : base("name=course_managementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<courses> courses { get; set; }
        public virtual DbSet<management> management { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<teachers> teachers { get; set; }
    }
}
